spring:
  application:
    name: blog
  datasource:
    url: jdbc:postgresql://localhost:5432/blog-db-1
    username: postgres
    password: password
    # driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      # database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect